export const PREDEFINED_BLOG_CATEGORIES = [
  'Training',
  'Health',
  'Nutrition',
  'Grooming',
  'Behavior',
  'Puppies',
  'Senior Dogs',
  'Breeds',
  'Adoption',
  'Travel',
  'Accessories',
  'Seasonal',
  'Safety',
  'Events',
  'Tips & Tricks',
  'DIY',
  'Dog Sports',
  'Rescue',
  'Veterinary Care',
  'Stories',
] as const;
